version: "3.8"
services:
  backend:
    build: ./backend
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_USER_POOL_ID=${AWS_USER_POOL_ID}
      - AWS_APP_CLIENT_ID=${AWS_APP_CLIENT_ID}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - /backend/tmp
  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_AWS_REGION=${AWS_REGION}
      - NEXT_PUBLIC_AWS_USER_POOL_ID=${AWS_USER_POOL_ID}
      - NEXT_PUBLIC_AWS_APP_CLIENT_ID=${AWS_APP_CLIENT_ID}
      - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
