version: "3.8"
services:
  backend:
    build: ./backend
    environment:
      - SUPABASE_URL={SUPABASE_URL}
      - SUPABASE_ANON_KEY={SUPABASE_ANON_KEY}
      - DB_URL={DB_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - /backend/tmp
  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SUPABASE_BUCKET_NAME=${SUPABASE_BUCKET_NAME}
      - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
