// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ID             uuid.UUID
	AuthorID       sql.NullString
	Message        string
	HeadActivityID uuid.NullUUID
	ExpiresAt      time.Time
	CreatedAt      time.Time
}

type Message struct {
	ID         uuid.UUID
	SenderID   sql.NullString
	ReceiverID sql.NullString
	Message    sql.NullString
	CreateAt   sql.NullTime
}

type Relationship struct {
	ID         uuid.UUID
	FollowedID sql.NullString
	FollowerID sql.NullString
}

type User struct {
	ID          string
	DisplayName string
	AvatarUrl   string
}
