// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ID             uuid.UUID     `json:"id"`
	AuthorID       uuid.UUID     `json:"author_id"`
	Message        string        `json:"message"`
	HeadActivityID uuid.NullUUID `json:"head_activity_id"`
	ExpiresAt      time.Time     `json:"expires_at"`
	CreatedAt      time.Time     `json:"created_at"`
}

type Message struct {
	ID         uuid.UUID `json:"id"`
	SenderID   uuid.UUID `json:"sender_id"`
	ReceiverID uuid.UUID `json:"receiver_id"`
	Message    string    `json:"message"`
	CreateAt   time.Time `json:"create_at"`
}

type Relationship struct {
	FollowedID uuid.UUID `json:"followed_id"`
	FollowerID uuid.UUID `json:"follower_id"`
}

type User struct {
	ID          uuid.UUID `json:"id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
	AvatarUrl   string    `json:"avatar_url"`
}
